//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_User_Roles
    {
        public long Admin_User_Role_Id { get; set; }
        public long Admin_User_Id { get; set; }
        public long Admin_Project_Id { get; set; }
        public long Admin_Role_Id { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
    
        public virtual Biz_Admin_Roles Biz_Admin_Roles { get; set; }
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
    }
}
