//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_CoBrowse_Log
    {
        public long CoBrowseLogId { get; set; }
        public string Project { get; set; }
        public long AdminUserId { get; set; }
        public Nullable<long> AppUserId { get; set; }
        public System.Guid UniqueId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is_Co_Edit { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTimeStamp { get; set; }
        public System.DateTime UpdateTimeStamp { get; set; }
        public Nullable<System.Guid> App_User_Guid { get; set; }
    }
}
