//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_SpanPlan_Lead_Log
    {
        public long Admin_Lead_Log_Id { get; set; }
        public string Business_Name { get; set; }
        public string Status_Change { get; set; }
        public string Business_Type { get; set; }
        public string Address { get; set; }
        public string Website_Address { get; set; }
        public string City { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone_Number { get; set; }
        public string Main_Contact { get; set; }
        public string Mobile_Number { get; set; }
        public string Position { get; set; }
        public string Email_Address { get; set; }
        public string Last_Contacted_By { get; set; }
        public string Preferred_Method_Contact { get; set; }
        public System.DateTime Last_Contacted_Date { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public Nullable<System.DateTime> LeadLog_Date { get; set; }
    }
}
