//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_LeadLog_Notes
    {
        public long Biz_Admin_LeadLog_Note_Id { get; set; }
        public long Admin_LeadLog_Id { get; set; }
        public string Comments { get; set; }
        public string Support_Type { get; set; }
        public string Admin_User_Name { get; set; }
        public Nullable<System.DateTime> Followup_Date { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Biz_Admin_LeadLog Biz_Admin_LeadLog { get; set; }
    }
}
