//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_User_Payments_Logs
    {
        public long User_Payment_Log_Id { get; set; }
        public System.Guid User_Payment_Id { get; set; }
        public Nullable<long> Admin_User_Id { get; set; }
        public string Acitivity_Msg { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Actity_Type { get; set; }
    
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
        public virtual Biz_User_Payments Biz_User_Payments { get; set; }
    }
}
