//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Follow_Up_Log
    {
        public long Support_Follow_Up_Id { get; set; }
        public long Campaign_Assigned_Details_Id { get; set; }
        public Nullable<long> Campaign_Details_Id { get; set; }
        public Nullable<long> Admin_User_Id { get; set; }
        public Nullable<long> Support_User_Id { get; set; }
        public bool Is_Phone { get; set; }
        public bool Is_Email { get; set; }
        public bool Is_Spoke { get; set; }
        public bool Is_Voice_Email { get; set; }
        public bool Is_Left_Voice_Mail { get; set; }
        public Nullable<bool> Is_No_Voice_Mail { get; set; }
        public string Contact_Name { get; set; }
        public bool Is_Uses_Us { get; set; }
        public bool Is_Spanish_Speaker { get; set; }
        public string Comments { get; set; }
        public bool Is_Follow_up { get; set; }
        public Nullable<System.DateTime> Follow_Up_Date { get; set; }
        public string Reason { get; set; }
        public string OtherReason { get; set; }
        public string Other_Service_Name { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
        public virtual Biz_Admin_Users Biz_Admin_Users1 { get; set; }
        public virtual Biz_Campaign_Assigned_Details Biz_Campaign_Assigned_Details { get; set; }
        public virtual Biz_Campaign_Details Biz_Campaign_Details { get; set; }
    }
}
