//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Manager_Follow_Up_Details
    {
        public Biz_Campaign_Manager_Follow_Up_Details()
        {
            this.Biz_Campaign_Assigned_Details = new HashSet<Biz_Campaign_Assigned_Details>();
        }
    
        public int Campaign_Follow_Up_Id { get; set; }
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Phone { get; set; }
        public string User_Email_Address { get; set; }
        public string Comments { get; set; }
        public int Admin_User_Id { get; set; }
        public string Campaign_Status { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    
        public virtual ICollection<Biz_Campaign_Assigned_Details> Biz_Campaign_Assigned_Details { get; set; }
    }
}
