//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_User_Payments
    {
        public Biz_User_Payments()
        {
            this.Biz_User_Payments_Logs = new HashSet<Biz_User_Payments_Logs>();
        }
    
        public System.Guid User_Payment_Id { get; set; }
        public int Project_id { get; set; }
        public string Order_Description { get; set; }
        public string Payment_Status { get; set; }
        public string Card_No { get; set; }
        public string Name_On_Card { get; set; }
        public string Card_Expiry { get; set; }
        public string Payment_Processor { get; set; }
        public string Payment_Approval_Code { get; set; }
        public string From_Email { get; set; }
        public string To_Email { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public string Business_Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<long> Country_Id { get; set; }
        public string Postal_Zip_Code { get; set; }
        public string Mail_Body_S3_Path { get; set; }
        public string Message_Id { get; set; }
        public Nullable<System.DateTime> Mail_Sent_Time { get; set; }
        public Nullable<System.DateTime> Paid_Time { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Mail_Subject { get; set; }
        public string Mail_Fail_Msg { get; set; }
        public string Phone_No { get; set; }
        public string Receipt_S3_Path { get; set; }
        public string Product_User_Id { get; set; }
        public string Invoice_No { get; set; }
    
        public virtual ICollection<Biz_User_Payments_Logs> Biz_User_Payments_Logs { get; set; }
        public virtual Static_Biz_Admin_Countries Static_Biz_Admin_Countries { get; set; }
        public virtual Static_Biz_Admin_Project Static_Biz_Admin_Project { get; set; }
        public virtual Static_Biz_Admin_States Static_Biz_Admin_States { get; set; }
    }
}
