//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_LeadLog
    {
        public Biz_Admin_LeadLog()
        {
            this.Biz_Admin_LeadLog_Follow = new HashSet<Biz_Admin_LeadLog_Follow>();
            this.Biz_Admin_LeadLog_Notes = new HashSet<Biz_Admin_LeadLog_Notes>();
        }
    
        public long Admin_Lead_Log_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Website_Address { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Preferred_Method_Contact { get; set; }
        public int Star_Rating { get; set; }
        public string Status_Change { get; set; }
        public Nullable<System.DateTime> Follow_Up_Date { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
        public string Admin_User_Name { get; set; }
        public string Project { get; set; }
        public string FollowUp_Message { get; set; }
        public string State { get; set; }
        public string Position { get; set; }
        public string Country { get; set; }
        public string Lead_Source { get; set; }
        public string Lead_Deleted_By { get; set; }
        public Nullable<System.DateTime> LeadLog_Date { get; set; }
        public Nullable<bool> Is_Do_Not_FollowUp { get; set; }
        public string Business_Name { get; set; }
    
        public virtual ICollection<Biz_Admin_LeadLog_Follow> Biz_Admin_LeadLog_Follow { get; set; }
        public virtual ICollection<Biz_Admin_LeadLog_Notes> Biz_Admin_LeadLog_Notes { get; set; }
    }
}
