//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Windows_Services
    {
        public Biz_Windows_Services()
        {
            this.Biz_Windows_Service_Activity_Log = new HashSet<Biz_Windows_Service_Activity_Log>();
        }
    
        public long Service_Id { get; set; }
        public int Server_Id { get; set; }
        public string Service_Name { get; set; }
        public string Service_Description { get; set; }
        public string Service_Status { get; set; }
        public string Service_Action { get; set; }
        public string Service_Path { get; set; }
        public bool Is_Safe_Stop_Configured { get; set; }
        public string Safe_Stop_Config_Path { get; set; }
        public string Controller_Exception { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public bool Is_Mail_Notify { get; set; }
        public bool Is_SMS_Notify { get; set; }
        public Nullable<System.DateTime> Last_SMS_Sent_Time { get; set; }
    
        public virtual ICollection<Biz_Windows_Service_Activity_Log> Biz_Windows_Service_Activity_Log { get; set; }
    }
}
