//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Additional_Contacts_Details
    {
        public long Additional_Contacts_Details_Id { get; set; }
        public long Campaign_Assigned_Details_Id { get; set; }
        public string Contacts_Name { get; set; }
        public string Contacts_Title { get; set; }
        public string Contacts_Email_Address { get; set; }
        public string Contacts_Phone_Number { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    
        public virtual Biz_Campaign_Assigned_Details Biz_Campaign_Assigned_Details { get; set; }
    }
}
