//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_Log
    {
        public long Admin_Log_Id { get; set; }
        public System.DateTime Log_Date { get; set; }
        public string Admin_User_Name { get; set; }
        public string User_Name { get; set; }
        public string Support_Type { get; set; }
        public string Comments { get; set; }
        public string Project { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
        public string Phone_Number { get; set; }
        public string Email_Address { get; set; }
        public Nullable<long> Category_Id { get; set; }
        public Nullable<System.DateTime> Follow_Up_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Star_Rating { get; set; }
        public string Caller { get; set; }
    }
}
