//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Excel_Headers
    {
        public Biz_Campaign_Excel_Headers()
        {
            this.Biz_Campaign_Excel_Values = new HashSet<Biz_Campaign_Excel_Values>();
        }
    
        public long Campaign_Excel_Header_Id { get; set; }
        public long Campaign_Details_Id { get; set; }
        public string Header_Name { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    
        public virtual Biz_Campaign_Details Biz_Campaign_Details { get; set; }
        public virtual ICollection<Biz_Campaign_Excel_Values> Biz_Campaign_Excel_Values { get; set; }
    }
}
