//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Details
    {
        public Biz_Campaign_Details()
        {
            this.Biz_Campaign_Assigned_Details = new HashSet<Biz_Campaign_Assigned_Details>();
            this.Biz_Campaign_Excel_Headers = new HashSet<Biz_Campaign_Excel_Headers>();
            this.Biz_Campaign_Follow_Up_Log = new HashSet<Biz_Campaign_Follow_Up_Log>();
            this.Biz_Campaign_Lead_Activity = new HashSet<Biz_Campaign_Lead_Activity>();
            this.Biz_Campaign_Support_User_Details = new HashSet<Biz_Campaign_Support_User_Details>();
        }
    
        public long Campaign_Details_Id { get; set; }
        public long Admin_User_Id { get; set; }
        public string Campaign_Name { get; set; }
        public string Campaign_File_Name { get; set; }
        public string File_Path { get; set; }
        public string Goals { get; set; }
        public int No_Of_Leads { get; set; }
        public string Unique_Id { get; set; }
        public bool Is_Deleted { get; set; }
        public bool Is_Paused { get; set; }
        public bool Is_Suspended { get; set; }
        public Nullable<int> Admin_Project_Id { get; set; }
        public Nullable<System.DateTime> Campaign_Start_Date { get; set; }
        public Nullable<System.DateTime> Campaign_End_Date { get; set; }
        public bool Is_Upload_File_Assign { get; set; }
        public bool Is_Discarded_Request { get; set; }
        public string Notes { get; set; }
        public string Discarded_Reason { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
        public string Tech_Team_Status { get; set; }
        public string Campaign_Type { get; set; }
        public Nullable<System.DateTime> Tech_Team_File_Uploaded_Time { get; set; }
        public string DemoGrapic_Information { get; set; }
        public string SuspendReason { get; set; }
        public Nullable<System.DateTime> SuspendDate { get; set; }
        public string Batch_Status { get; set; }
        public bool Is_Manager_Follow_Up { get; set; }
    
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
        public virtual ICollection<Biz_Campaign_Assigned_Details> Biz_Campaign_Assigned_Details { get; set; }
        public virtual Biz_Campaign_Details Biz_Campaign_Details1 { get; set; }
        public virtual Biz_Campaign_Details Biz_Campaign_Details2 { get; set; }
        public virtual Static_Biz_Admin_Project Static_Biz_Admin_Project { get; set; }
        public virtual ICollection<Biz_Campaign_Excel_Headers> Biz_Campaign_Excel_Headers { get; set; }
        public virtual ICollection<Biz_Campaign_Follow_Up_Log> Biz_Campaign_Follow_Up_Log { get; set; }
        public virtual ICollection<Biz_Campaign_Lead_Activity> Biz_Campaign_Lead_Activity { get; set; }
        public virtual ICollection<Biz_Campaign_Support_User_Details> Biz_Campaign_Support_User_Details { get; set; }
    }
}
