//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Campaign_Lead_Activity
    {
        public long Campaign_Lead_Activity_Id { get; set; }
        public long Campaign_Assign_Detail_Id { get; set; }
        public long Campaign_Detail_Id { get; set; }
        public long Support_User_Id { get; set; }
        public string Email_Address { get; set; }
        public string Method_Of_Contact { get; set; }
        public string Type_Of_Call { get; set; }
        public string Spoke_To { get; set; }
        public string Comments { get; set; }
        public bool Is_Do_Not_Disturb { get; set; }
        public string Reason { get; set; }
        public bool Is_Follow_Up { get; set; }
        public Nullable<System.DateTime> Followup_Date { get; set; }
        public Nullable<System.TimeSpan> Followup_Time { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Lead_Status { get; set; }
        public string Other_Reason { get; set; }
        public Nullable<bool> Is_Notified { get; set; }
    
        public virtual Biz_Campaign_Assigned_Details Biz_Campaign_Assigned_Details { get; set; }
        public virtual Biz_Campaign_Details Biz_Campaign_Details { get; set; }
    }
}
