//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Ip_Address
    {
        public long Ip_Address_Id { get; set; }
        public Nullable<int> Project_id { get; set; }
        public string Ip_Address { get; set; }
        public string Ip_Name { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public Nullable<bool> Is_Static { get; set; }
    
        public virtual Static_Biz_Admin_Project Static_Biz_Admin_Project { get; set; }
    }
}
