//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_SCActivityLog
    {
        public long SCActivityLog_Id { get; set; }
        public Nullable<long> Admin_User_Id { get; set; }
        public string Ip_Address { get; set; }
        public string Visted_URL { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public string Action { get; set; }
        public string Additional_Info_1 { get; set; }
        public string Additional_Info_2 { get; set; }
        public string Additional_Info_3 { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<System.DateTime> Create_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Update_Time_Stamp { get; set; }
    }
}
