//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Admin_Roles
    {
        public Biz_Admin_Roles()
        {
            this.Biz_Admin_User_Roles = new HashSet<Biz_Admin_User_Roles>();
            this.Biz_Admin_Users = new HashSet<Biz_Admin_Users>();
        }
    
        public long Admin_Role_Id { get; set; }
        public string Admin_Role { get; set; }
        public string Description { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Category_Ids { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual ICollection<Biz_Admin_User_Roles> Biz_Admin_User_Roles { get; set; }
        public virtual ICollection<Biz_Admin_Users> Biz_Admin_Users { get; set; }
    }
}
