//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainControlDB_Entities : DbContext
    {
        public MainControlDB_Entities()
            : base("name=MainControlDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Biz_Admin_LeadLog> Biz_Admin_LeadLog { get; set; }
        public DbSet<Biz_Admin_LeadLog_Follow> Biz_Admin_LeadLog_Follow { get; set; }
        public DbSet<Biz_Admin_LeadLog_Notes> Biz_Admin_LeadLog_Notes { get; set; }
        public DbSet<Biz_Admin_Log> Biz_Admin_Log { get; set; }
        public DbSet<Biz_Admin_Roles> Biz_Admin_Roles { get; set; }
        public DbSet<Biz_Admin_SpanPlan_Lead_Log> Biz_Admin_SpanPlan_Lead_Log { get; set; }
        public DbSet<Biz_Admin_SpanPlan_Lead_Log_Follow> Biz_Admin_SpanPlan_Lead_Log_Follow { get; set; }
        public DbSet<Biz_Admin_User_Roles> Biz_Admin_User_Roles { get; set; }
        public DbSet<Biz_Admin_Users> Biz_Admin_Users { get; set; }
        public DbSet<Biz_Campaign_Additional_Contacts_Details> Biz_Campaign_Additional_Contacts_Details { get; set; }
        public DbSet<Biz_Campaign_Assigned_Details> Biz_Campaign_Assigned_Details { get; set; }
        public DbSet<Biz_Campaign_Details> Biz_Campaign_Details { get; set; }
        public DbSet<Biz_Campaign_Excel_Headers> Biz_Campaign_Excel_Headers { get; set; }
        public DbSet<Biz_Campaign_Excel_Values> Biz_Campaign_Excel_Values { get; set; }
        public DbSet<Biz_Campaign_Follow_Up_Log> Biz_Campaign_Follow_Up_Log { get; set; }
        public DbSet<Biz_Campaign_Lead_Activity> Biz_Campaign_Lead_Activity { get; set; }
        public DbSet<Biz_Campaign_Manager_Follow_Up_Details> Biz_Campaign_Manager_Follow_Up_Details { get; set; }
        public DbSet<Biz_Campaign_Support_User_Details> Biz_Campaign_Support_User_Details { get; set; }
        public DbSet<Biz_CoBrowse_Log> Biz_CoBrowse_Log { get; set; }
        public DbSet<Biz_Ip_Address> Biz_Ip_Address { get; set; }
        public DbSet<Biz_SCActivityLog> Biz_SCActivityLog { get; set; }
        public DbSet<Biz_Servers> Biz_Servers { get; set; }
        public DbSet<Biz_User_Payments> Biz_User_Payments { get; set; }
        public DbSet<Biz_User_Payments_Logs> Biz_User_Payments_Logs { get; set; }
        public DbSet<Biz_Windows_Service_Activity_Log> Biz_Windows_Service_Activity_Log { get; set; }
        public DbSet<Biz_Windows_Services> Biz_Windows_Services { get; set; }
        public DbSet<Gmail_User_Details> Gmail_User_Details { get; set; }
        public DbSet<Mobile_Verification> Mobile_Verification { get; set; }
        public DbSet<Sc_Activity_Log> Sc_Activity_Log { get; set; }
        public DbSet<SC_Authorize_Payment_Report> SC_Authorize_Payment_Report { get; set; }
        public DbSet<SC_Static_Authorize_Credential> SC_Static_Authorize_Credential { get; set; }
        public DbSet<Static_Biz_Admin_Category> Static_Biz_Admin_Category { get; set; }
        public DbSet<Static_Biz_Admin_Category_Project> Static_Biz_Admin_Category_Project { get; set; }
        public DbSet<Static_Biz_Admin_Countries> Static_Biz_Admin_Countries { get; set; }
        public DbSet<Static_Biz_Admin_Log_Category> Static_Biz_Admin_Log_Category { get; set; }
        public DbSet<Static_Biz_Admin_Positions> Static_Biz_Admin_Positions { get; set; }
        public DbSet<Static_Biz_Admin_Project> Static_Biz_Admin_Project { get; set; }
        public DbSet<Static_Biz_Admin_States> Static_Biz_Admin_States { get; set; }
        public DbSet<Static_Biz_Lead_Status> Static_Biz_Lead_Status { get; set; }
        public DbSet<Static_Biz_Lead_Status_Details> Static_Biz_Lead_Status_Details { get; set; }
        public DbSet<Static_Biz_Mail_templates> Static_Biz_Mail_templates { get; set; }
        public DbSet<Static_Biz_Payment_Templates> Static_Biz_Payment_Templates { get; set; }
        public DbSet<Static_Biz_Span_Service_Finders> Static_Biz_Span_Service_Finders { get; set; }
        public DbSet<Support_User_Instructions> Support_User_Instructions { get; set; }
        public DbSet<Tax_Lead_Log> Tax_Lead_Log { get; set; }
        public DbSet<Tax_Lead_Log_Follow> Tax_Lead_Log_Follow { get; set; }
    }
}
