//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Verification
    {
        public long Mobile_Verification_Id { get; set; }
        public long User_Id { get; set; }
        public string Verification_Code { get; set; }
        public string Phone_Number { get; set; }
        public string Unique_Id { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime UpdateT_ime_Stamp { get; set; }
    
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
    }
}
