//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sc_Activity_Log
    {
        public long Sc_Activity_Log_Id { get; set; }
        public string Action_Type { get; set; }
        public System.DateTime Activity_Date { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public string Display_Name { get; set; }
        public string Controller_Name { get; set; }
        public string Action_Name { get; set; }
        public string IP_Address { get; set; }
        public string Activity { get; set; }
        public string Memo { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
    
        public virtual Biz_Admin_Users Biz_Admin_Users { get; set; }
    }
}
