//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_Authorize_Payment_Report
    {
        public long SC_Authorize_Payment_Report_Id { get; set; }
        public Nullable<System.DateTime> Transaction_Settlement_Date { get; set; }
        public Nullable<long> Authorize_Credential_Id { get; set; }
        public string Product_Code { get; set; }
        public Nullable<decimal> Settled_Amount { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    
        public virtual SC_Static_Authorize_Credential SC_Static_Authorize_Credential { get; set; }
    }
}
