//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_Static_Authorize_Credential
    {
        public SC_Static_Authorize_Credential()
        {
            this.SC_Authorize_Payment_Report = new HashSet<SC_Authorize_Payment_Report>();
        }
    
        public long Authorize_Credential_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Code { get; set; }
        public string Authorize_Login_Key { get; set; }
        public string Authorize_Transaction_Key { get; set; }
        public bool Is_Daily_Report_Active { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
        public string Payment_Processor_Type { get; set; }
        public string ACI_Login { get; set; }
        public string ACI_Password { get; set; }
        public Nullable<long> ACI_Division_Id { get; set; }
        public Nullable<long> ACI_Business_Id { get; set; }
        public Nullable<bool> Is_Amex_Login { get; set; }
    
        public virtual ICollection<SC_Authorize_Payment_Report> SC_Authorize_Payment_Report { get; set; }
    }
}
