//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Static_Biz_Lead_Status_Details
    {
        public long Lead_Status_detailsId { get; set; }
        public Nullable<long> Lead_StatusId { get; set; }
        public string Lead_Status_details { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
