//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Static_Biz_Admin_Category
    {
        public int Category_Id { get; set; }
        public string Category_Name { get; set; }
        public string Category_Description { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<short> Display_Order { get; set; }
        public Nullable<System.DateTime> Create_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Update_Time_Stamp { get; set; }
    }
}
