//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Static_Biz_Payment_Templates
    {
        public int Payment_Template_Id { get; set; }
        public string Template_Html { get; set; }
        public int Project_Id { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Mail_Subject { get; set; }
    
        public virtual Static_Biz_Admin_Project Static_Biz_Admin_Project { get; set; }
    }
}
