//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Control.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Lead_Log
    {
        public Tax_Lead_Log()
        {
            this.Tax_Lead_Log_Follow = new HashSet<Tax_Lead_Log_Follow>();
        }
    
        public long Lead_Log_Id { get; set; }
        public string Business_Name { get; set; }
        public string Business_Type { get; set; }
        public string Type_of_User { get; set; }
        public string Contact_Name { get; set; }
        public string Email_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public string Website_Address { get; set; }
        public string Preferred_Method_of_Contact { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Lead_Source { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Logged_Date { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Is_ETT { get; set; }
        public Nullable<int> No_of_Trucks_Ett { get; set; }
        public Nullable<int> No_of_Owner_Operators_Ett { get; set; }
        public string Feature_Looking_for { get; set; }
        public Nullable<int> No_of_Returns_Filed_per_year { get; set; }
        public string Interested_Forms { get; set; }
        public Nullable<bool> Is_ETF { get; set; }
        public string Interested_Forms_Etf { get; set; }
        public Nullable<int> No_of_Contractors { get; set; }
        public Nullable<int> No_of_Employees { get; set; }
        public string Feature_Looking_for_Etf { get; set; }
        public Nullable<bool> Is_IFTA { get; set; }
        public Nullable<int> No_of_Trucks_Ifta { get; set; }
        public Nullable<int> No_of_Owner_Operators_Ifta { get; set; }
        public string Feature_Looking_for_Ifta { get; set; }
        public string Interested_Forms_Ifta { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
        public string Others_Text_Ett { get; set; }
        public string Others_Text_Etf { get; set; }
        public string Others_Text_Ifta { get; set; }
        public Nullable<long> Admin_User_Id { get; set; }
        public string Admin_User_Name { get; set; }
        public string Other_Business_Type { get; set; }
        public string Other_Lead_Source { get; set; }
        public string City { get; set; }
        public string Zip_Code { get; set; }
        public string DBA_Name { get; set; }
        public string EIN { get; set; }
        public Nullable<long> Sales_Person_Id { get; set; }
    
        public virtual ICollection<Tax_Lead_Log_Follow> Tax_Lead_Log_Follow { get; set; }
    }
}
