//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Configuration;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "SpanWebServiceSoap", Namespace = "http://tempuri.org/")]
public partial class MainWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

    private System.Threading.SendOrPostCallback PdfKeyOperationCompleted;

    private System.Threading.SendOrPostCallback CopyRightYearOperationCompleted;

    /// <remarks/>
    public MainWebService()
    {
        this.Url = ConfigurationManager.AppSettings["MainUtilService"].ToString();
    }

    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;

    /// <remarks/>
    public event PdfKeyCompletedEventHandler PdfKeyCompleted;

    /// <remarks/>
    public event CopyRightYearCompletedEventHandler CopyRightYearCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld()
    {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void HelloWorldAsync()
    {
        this.HelloWorldAsync(null);
    }

    /// <remarks/>
    public void HelloWorldAsync(object userState)
    {
        if ((this.HelloWorldOperationCompleted == null))
        {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }

    private void OnHelloWorldOperationCompleted(object arg)
    {
        if ((this.HelloWorldCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PdfKey", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string PdfKey()
    {
        object[] results = this.Invoke("PdfKey", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginPdfKey(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("PdfKey", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndPdfKey(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void PdfKeyAsync()
    {
        this.PdfKeyAsync(null);
    }

    /// <remarks/>
    public void PdfKeyAsync(object userState)
    {
        if ((this.PdfKeyOperationCompleted == null))
        {
            this.PdfKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPdfKeyOperationCompleted);
        }
        this.InvokeAsync("PdfKey", new object[0], this.PdfKeyOperationCompleted, userState);
    }

    private void OnPdfKeyOperationCompleted(object arg)
    {
        if ((this.PdfKeyCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PdfKeyCompleted(this, new PdfKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CopyRightYear", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CopyRightYear()
    {
        object[] results = this.Invoke("CopyRightYear", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCopyRightYear(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CopyRightYear", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string EndCopyRightYear(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void CopyRightYearAsync()
    {
        this.CopyRightYearAsync(null);
    }

    /// <remarks/>
    public void CopyRightYearAsync(object userState)
    {
        if ((this.CopyRightYearOperationCompleted == null))
        {
            this.CopyRightYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyRightYearOperationCompleted);
        }
        this.InvokeAsync("CopyRightYear", new object[0], this.CopyRightYearOperationCompleted, userState);
    }

    private void OnCopyRightYearOperationCompleted(object arg)
    {
        if ((this.CopyRightYearCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CopyRightYearCompleted(this, new CopyRightYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void PdfKeyCompletedEventHandler(object sender, PdfKeyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PdfKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal PdfKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void CopyRightYearCompletedEventHandler(object sender, CopyRightYearCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CopyRightYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CopyRightYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
